const japKanjiData = [ 
{ "myId":0, "name": "学生", "prononciation":"gakusei", "translation":"Etudiant", "type": "nom", "family":"kanji",  "level":1},
{ "myId":1, "name": "英語", "prononciation":"eigo", "translation":"anglais", "type": "nom", "family":"kanji",  "level":1},
{ "myId":2, "name": "会社", "prononciation":"kaisha", "translation":"entreprise", "type": "nom", "family":"kanji",  "level":1},
{ "myId":3, "name": "日本", "prononciation":"nihon", "translation":"Japon", "type": "nom", "family":"kanji",  "level":1},
{ "myId":4, "name": "学校", "prononciation":"gakkou", "translation":"Ecole", "type": "nom", "family":"kanji",  "level":1},
{ "myId":5, "name": "時", "prononciation":"toki/ji", "translation":"Heure", "type": "adv", "family":"kanji",  "level":1},
{ "myId":6, "name": "今", "prononciation":"ima/kon", "translation":"Maintenant", "type": "adv", "family":"kanji",  "level":1},
{ "myId":7, "name": "月曜日", "prononciation":"getsuyoubi", "translation":"Lundi", "type": "nom", "family":"kanji",  "level":1},
{ "myId":8, "name": "５月", "prononciation":"go gatsu", "translation":"Mai ", "type": "nom", "family":"kanji",  "level":1},
{ "myId":9, "name": "２０１６年", "prononciation":"2016nen", "translation":"2016", "type": "nom", "family":"kanji",  "level":1},
{ "myId":10, "name": "犬", "prononciation":"inu", "translation":"dog", "type": "nom", "family":"kanji",  "level":1},
{ "myId":11, "name": "鳥", "prononciation":"toru", "translation":"bird", "type": "nom", "family":"kanji",  "level":1},
{ "myId":12, "name": "椅子", "prononciation":"isu", "translation":"chair", "type": "nom", "family":"kanji",  "level":1},
{ "myId":13, "name": "机", "prononciation":"tsukue", "translation":"desk", "type": "nom", "family":"kanji",  "level":1},
{ "myId":14, "name": "百 ", "prononciation":"hiaku", "translation":"one hundred", "type": "adv", "family":"kanji",  "level":1},
{ "myId":15, "name": "千 ", "prononciation":"Sentaku", "translation":"one thousand", "type": "adv", "family":"kanji",  "level":1},
{ "myId":16, "name": "万 ", "prononciation":"man", "translation":"ten thousand", "type": "adv", "family":"kanji",  "level":1},
{ "myId":17, "name": "自転車", "prononciation":"jitensha", "translation":"vélo", "type": "nom", "family":"kanji",  "level":1},
{ "myId":18, "name": "地図", "prononciation":"chiizu", "translation":"carte", "type": "nom", "family":"kanji",  "level":1},
{ "myId":19, "name": "乗ります", "prononciation":"norimasu", "translation":"monter", "type": "vb", "family":"kanji",  "level":1},
{ "myId":20, "name": "新しい", "prononciation":"atarashii", "translation":"nouveau", "type": "adj", "family":"kanji",  "level":1},
{ "myId":21, "name": "着ます", "prononciation":"kimasu", "translation":"Porter(haut)", "type": "vb", "family":"kanji",  "level":1},
{ "myId":22, "name": "履きます", "prononciation":" Hakimasu", "translation":"Porter(bas)", "type": "vb", "family":"kanji",  "level":1},
{ "myId":23, "name": "服", "prononciation":"fuku", "translation":"vêtements", "type": "nom", "family":"kanji",  "level":1},
{ "myId":24, "name": "洗います", "prononciation":"haraimasu", "translation":"Laver", "type": "vb", "family":"kanji",  "level":1},
{ "myId":25, "name": "脱ぎます", "prononciation":"nugimasu", "translation":"Enlever", "type": "vb", "family":"kanji",  "level":1},
{ "myId":26, "name": "茶色", "prononciation":"chairo", "translation":"marron", "type": "adj", "family":"kanji",  "level":1},
{ "myId":27, "name": "黒い", "prononciation":"kuroi", "translation":"Noir", "type": "adj", "family":"kanji",  "level":1},
{ "myId":28, "name": "一緒", "prononciation":"Ishounii", "translation":"Ensemble", "type": "adv", "family":"kanji",  "level":1},
{ "myId":29, "name": "走ります", "prononciation":"Ashirimasu", "translation":"Courir", "type": "vb", "family":"kanji",  "level":1},
{ "myId":30, "name": "来ま", "prononciation":"Kimasu", "translation":"venir", "type": "vb", "family":"kanji",  "level":1},
{ "myId":31, "name": "電話", "prononciation":"Denwa", "translation":"telephone", "type": "nom", "family":"kanji",  "level":1},
{ "myId":32, "name": "ホテル", "prononciation":"", "translation":"hotel", "type": "nom", "family":"katakana",  "level":1},
{ "myId":33, "name": "弾きます", "prononciation":"Hikimasu", "translation":"Jouer(instruments à cordes + piano)", "type": "vb", "family":"kanji",  "level":1},
{ "myId":34, "name": "ギター", "prononciation":"", "translation":"Guitare", "type": "nom", "family":"katakana",  "level":1},
{ "myId":35, "name": "昨日", "prononciation":"Kinou", "translation":"hier", "type": "adv", "family":"kanji",  "level":1},
{ "myId":36, "name": "好き", "prononciation":" Suki", "translation":"Aimer", "type": "vb", "family":"kanji",  "level":1},
{ "myId":37, "name": "料理", "prononciation":" Ryouri", "translation":"Cuisiner", "type": "vb", "family":"kanji",  "level":1},
{ "myId":38, "name": "パソコン", "prononciation":"", "translation":"PC", "type": "nom", "family":"katakana",  "level":1},
{ "myId":39, "name": "新聞", "prononciation":"Shinbun", "translation":"journal", "type": "nom", "family":"kanji",  "level":1},
{ "myId":40, "name": "大丈夫", "prononciation":"Daijoubu", "translation":" Ca va/non merci", "type": "int", "family":"kanji",  "level":1},
{ "myId":41, "name": "強い", "prononciation":"tsuyoi", "translation":"fort", "type": "adj", "family":"kanji",  "level":1},
{ "myId":42, "name": "風", "prononciation":"Kaze", "translation":"vent", "type": "nom", "family":"kanji",  "level":1},
{ "myId":43, "name": "悪い", "prononciation":"warui", "translation":"mauvais", "type": "adj", "family":"kanji",  "level":1},
{ "myId":44, "name": "曇り", "prononciation":"Kumori", "translation":"Nuageux", "type": "adj", "family":"kanji",  "level":1},
{ "myId":45, "name": "降ります", "prononciation":"Furimasu", "translation":"Pleuvoir", "type": "vb", "family":"kanji",  "level":1},
{ "myId":46, "name": "大きい", "prononciation":"Ookii", "translation":"grand", "type": "adj", "family":"kanji",  "level":1},
{ "myId":47, "name": "夕べ", "prononciation":"Yube", "translation":"La nuit dernière", "type": "adv", "family":"kanji",  "level":1},
{ "myId":48, "name": "今朝", "prononciation":"Kesa", "translation":"Ce matin", "type": "adv", "family":"kanji",  "level":1},
{ "myId":49, "name": "明るい", "prononciation":"Akarui", "translation":"Eclairé", "type": "adj", "family":"kanji",  "level":1},
{ "myId":50, "name": "暗い", "prononciation":"Kurai", "translation":"sombre", "type": "adj", "family":"kanji",  "level":1},
{ "myId":51, "name": "会いまsu", "prononciation":"Aimasu", "translation":"rencontrer", "type": "vb", "family":"kanji",  "level":1},
{ "myId":52, "name": "暑い", "prononciation":"Atsui", "translation":"Chaud(hot)", "type": "adj", "family":"kanji",  "level":1},
{ "myId":53, "name": "暖かい", "prononciation":"Attakai", "translation":"Chaud(warm)", "type": "adj", "family":"kanji",  "level":1},
{ "myId":54, "name": "全く", "prononciation":"mattaku", "translation":"Pas du tout", "type": "adv", "family":"hiragana",  "level":1},
{ "myId":55, "name": "とても", "prononciation":"", "translation":"Beaucoup", "type": "adv", "family":"hiragana",  "level":1},
{ "myId":56, "name": "おいしい", "prononciation":"", "translation":"délicieux", "type": "adj", "family":"hiragana",  "level":1},
{ "myId":57, "name": "結構 ", "prononciation":"kekkou", "translation":"Assez/quite/non merci", "type": "adv", "family":"kanji",  "level":1},
{ "myId":58, "name": "夕飯", "prononciation":"Yuhan", "translation":"diner", "type": "nom", "family":"kanji",  "level":1},
{ "myId":59, "name": "果物", "prononciation":"Kudamono", "translation":"fruits", "type": "nom", "family":"kanji",  "level":1},
{ "myId":60, "name": "甘い", "prononciation":"Amai", "translation":" Doux/sucré", "type": "adj", "family":"kanji",  "level":1},
{ "myId":61, "name": "多い", "prononciation":"Ooi", "translation":"Beaucoup ( en quantité)", "type": "adv", "family":"kanji",  "level":1},
{ "myId":62, "name": "飲み物", "prononciation":"Nomimono", "translation":"boisson", "type": "nom", "family":"kanji",  "level":1},
{ "myId":63, "name": "食べ物", "prononciation":"Tabemono", "translation":"nourriture", "type": "nom", "family":"kanji",  "level":1},
{ "myId":64, "name": "お腹", "prononciation":"Onaka", "translation":"ventre", "type": "nom", "family":"kanji",  "level":1},
{ "myId":65, "name": "使いま", "prononciation":"Tsukaimasu", "translation":"utiliser", "type": "vb", "family":"kanji",  "level":1},
{ "myId":66, "name": "フォーク", "prononciation":"", "translation":"fourchette", "type": "nom", "family":"katakana",  "level":1},
{ "myId":67, "name": "ナイフ", "prononciation":"", "translation":"couteau", "type": "nom", "family":"kanji",  "level":1},
{ "myId":68, "name": "好物", "prononciation":"Koubutsu", "translation":"repas préféré", "type": "nom", "family":"kanji",  "level":1},
{ "myId":69, "name": "本当", "prononciation":"Hontou", "translation":"vrai ", "type": "adv", "family":"kanji",  "level":1},
{ "myId":70, "name": "ぶどう", "prononciation":"", "translation":"raisin", "type": "nom", "family":"hiragana",  "level":1},
{ "myId":71, "name": "スープ", "prononciation":"", "translation":"soupe", "type": "nom", "family":"katakana",  "level":1},
{ "myId":72, "name": "ワイン", "prononciation":"", "translation":"vin", "type": "nom", "family":"katakana",  "level":1},
{ "myId":73, "name": "寿司", "prononciation":"Sushi", "translation":"sushi", "type": "nom", "family":"kanji",  "level":2},
{ "myId":74, "name": "銀行", "prononciation":" Ginkou", "translation":"banque", "type": "nom", "family":"kanji",  "level":2},
{ "myId":75, "name": "狭い ", "prononciation":"semai", "translation":"Etroi/petit", "type": "adj", "family":"kanji",  "level":2},
{ "myId":76, "name": "建物", "prononciation":"Tatemono", "translation":"batiment", "type": "nom", "family":"kanji",  "level":2},
{ "myId":77, "name": "入り口", "prononciation":"Iriguchi", "translation":"entrée", "type": "nom", "family":"kanji",  "level":2},
{ "myId":78, "name": "", "prononciation":"konbini", "translation":"supérette", "type": "nom", "family":"kanji",  "level":2},
{ "myId":79, "name": "道", "prononciation":"Michi", "translation":"chemin", "type": "nom", "family":"kanji",  "level":2},
{ "myId":80, "name": "向こう", "prononciation":"Mukou", "translation":"Au bout/Là-bas", "type": "adv", "family":"kanji",  "level":2},
{ "myId":81, "name": "出ます", "prononciation":"Demasu", "translation":"quitter/sortir", "type": "vb", "family":"kanji",  "level":2},
{ "myId":82, "name": "降ります", "prononciation":"Orimasu", "translation":"Descendre", "type": "vb", "family":"kanji",  "level":2},
{ "myId":83, "name": "通り", "prononciation":"Toori", "translation":"  rue", "type": "nom", "family":"kanji",  "level":2},
{ "myId":84, "name": "はじめに", "prononciation":"", "translation":"Pour commencer", "type": "adv", "family":"kanji",  "level":2},
{ "myId":85, "name": "角", "prononciation":"Kaku/ kado", "translation":" corner", "type": "nom", "family":"kanji",  "level":2},
{ "myId":86, "name": "出かけます", "prononciation":"Dekakemasu", "translation":"sortir (de)", "type": "vb", "family":"kanji",  "level":2},
{ "myId":87, "name": "年", "prononciation":"Toshi", "translation":"année", "type": "nom", "family":"kanji",  "level":2},
{ "myId":88, "name": "三週間", "prononciation":"San shuukan", "translation":"3 semaines", "type": "adv", "family":"kanji",  "level":2},
{ "myId":89, "name": "毎週月曜日", "prononciation":"Maishuu Getsuyoubi", "translation":"Chaque lundi", "type": "adv", "family":"kanji",  "level":2},
{ "myId":90, "name": "夏休み", "prononciation":"Natsuyasumi", "translation":"Vacances d’été", "type": "nom", "family":"kanji",  "level":2},
{ "myId":91, "name": "お金", "prononciation":"Ohana", "translation":" fleur", "type": "nom", "family":"kanji",  "level":2},
{ "myId":92, "name": "荷物", "prononciation":"nimotsu", "translation":"bagages", "type": "nom", "family":"kanji",  "level":2},
{ "myId":93, "name": "財布", "prononciation":"saifu", "translation":"porte monnaie", "type": "nom", "family":"kanji",  "level":2},
{ "myId":94, "name": "腕時計", "prononciation":"Ude doke", "translation":" montre", "type": "nom", "family":"kanji",  "level":2},
{ "myId":95, "name": "どんな", "prononciation":"", "translation":"Quel (genre de)", "type": "adv", "family":"kanji",  "level":2},
{ "myId":96, "name": "他", "prononciation":"hoka", "translation":"autre", "type": "adv", "family":"kanji",  "level":2},
{ "myId":97, "name": "色々", "prononciation":"Iro iro", "translation":"Toute sorte", "type": "adv", "family":"kanji",  "level":2},
{ "myId":98, "name": "重い", "prononciation":" Omoi", "translation":" lourd", "type": "adj", "family":"kanji",  "level":2},
{ "myId":99, "name": "あげます", "prononciation":"Agemasu", "translation":"donner", "type": "vb", "family":"hiragana",  "level":2},
{ "myId":100, "name": "入れます", "prononciation":"Iremasu", "translation":"Rentrer/mettre dans", "type": "vb", "family":"kanji",  "level":2},
{ "myId":101, "name": "同じ", "prononciation":" Onaji", "translation":" même", "type": "adv", "family":"kanji",  "level":2},
{ "myId":102, "name": "持ちます", "prononciation":"Mochimasu", "translation":"porter", "type": "vb", "family":"kanji",  "level":2},
{ "myId":103, "name": "パン屋", "prononciation":" Panya", "translation":" boulangerie", "type": "nom", "family":"kanji",  "level":2},
{ "myId":104, "name": "売ります", "prononciation":"Urimasu", "translation":" Ne pas avoir besoin", "type": "vb", "family":"kanji",  "level":2},
{ "myId":105, "name": "要ります", "prononciation":" Irimasu", "translation":"Avoir besoin", "type": "vb", "family":"kanji",  "level":2},
{ "myId":106, "name": "土産", "prononciation":"Miyage", "translation":"cadeau", "type": "nom", "family":"kanji",  "level":2},
{ "myId":107, "name": "どなた/dare", "prononciation":"donata/dare", "translation":" Qui(est-ce)", "type": "adv", "family":"hiragana",  "level":2},
{ "myId":108, "name": "一人", "prononciation":" Hitori", "translation":" seul", "type": "adj", "family":"kanji",  "level":2},
{ "myId":109, "name": "少しい", "prononciation":"Sukoshii", "translation":" Peu", "type": "adv", "family":"kanji",  "level":2},
{ "myId":110, "name": "有名", "prononciation":"Yuume", "translation":"celebre", "type": "adj", "family":"kanji",  "level":2},
{ "myId":111, "name": "彼氏", "prononciation":" Kareshi", "translation":" Copain (amoureux)", "type": "nom", "family":"kanji",  "level":2},
{ "myId":112, "name": "去年", "prononciation":"Kyounen", "translation":"Année dernière", "type": "adv", "family":"kanji",  "level":2},
{ "myId":113, "name": "生まれま", "prononciation":"Umaremasu", "translation":"naitre", "type": "vb", "family":"kanji",  "level":2},
{ "myId":114, "name": "掃除", "prononciation":"Souji", "translation":"Nettoyer", "type": "vb", "family":"kanji",  "level":2},
{ "myId":115, "name": "帰ります", "prononciation":"Kaerimasu", "translation":" Rentrer (à la maison)", "type": "vb", "family":"kanji",  "level":2},
{ "myId":116, "name": "浴びます", "prononciation":"Abimasu", "translation":"Prendre(douche)", "type": "vb", "family":"kanji",  "level":2},
{ "myId":117, "name": "座って", "prononciation":"Suwatte", "translation":"Assis toi", "type": "vb", "family":"kanji",  "level":2},
{ "myId":118, "name": "書いてます", "prononciation":"Kaitemasu", "translation":" Ecrire ", "type": "vb", "family":"kanji",  "level":2},
{ "myId":119, "name": "早い", "prononciation":"Hayai", "translation":"A l'avance", "type": "adv", "family":"kanji",  "level":2},
{ "myId":120, "name": "電気", "prononciation":"Denki", "translation":"Electricité", "type": "nom", "family":"kanji",  "level":2},
{ "myId":121, "name": "持っています", "prononciation":"Motte imasu", "translation":" Posséder ", "type": "vb", "family":"kanji",  "level":2},
{ "myId":122, "name": "待ちます", "prononciation":"Machimasu", "translation":" Attendre", "type": "vb", "family":"kanji",  "level":2},
{ "myId":123, "name": "ゆっくり", "prononciation":"", "translation":"doucement", "type": "adv", "family":"kanji",  "level":2},
{ "myId":124, "name": "もう", "prononciation":"", "translation":" déjà", "type": "adv", "family":"hiragana",  "level":2},
{ "myId":125, "name": "授業", "prononciation":"Jugyou", "translation":" cours (école)", "type": "nom", "family":"kanji",  "level":2},
{ "myId":126, "name": "易しい", "prononciation":"Yasashii", "translation":" Gentil/facile", "type": "adj", "family":"kanji",  "level":2},
{ "myId":127, "name": "教科書", "prononciation":"kyoukashou", "translation":" Manuel scolaire", "type": "nom", "family":"kanji",  "level":2},
{ "myId":128, "name": "大学", "prononciation":"Daigaku", "translation":" Université", "type": "nom", "family":"kanji",  "level":2},
{ "myId":129, "name": "漢字", "prononciation":"Kanji", "translation":"kanji", "type": "nom", "family":"kanji",  "level":2},
{ "myId":130, "name": "意味", "prononciation":" Imi", "translation":" Sens", "type": "nom", "family":"kanji",  "level":2},
{ "myId":131, "name": "辞書", "prononciation":"jishou", "translation":" dictionnaire", "type": "nom", "family":"kanji",  "level":2},
{ "myId":132, "name": "では", "prononciation":"", "translation":"ok donc…", "type": "adv", "family":"hiragana",  "level":2},
{ "myId":133, "name": "山", "prononciation":" Yama", "translation":" montagne", "type": "nom", "family":"kanji",  "level":2},
{ "myId":134, "name": "木", "prononciation":" ki", "translation":" arbre", "type": "nom", "family":"kanji",  "level":2},
{ "myId":135, "name": "池", "prononciation":" ike", "translation":"étang", "type": "nom", "family":"kanji",  "level":2},
{ "myId":136, "name": "鳴きます", "prononciation":"Nakimasu", "translation":"Chanter(oiseau)/aboyer", "type": "vb", "family":"kanji",  "level":2},
{ "myId":137, "name": "うるさい", "prononciation":"", "translation":"bruyant", "type": "adj", "family":"hiragana",  "level":2},
{ "myId":138, "name": "はと", "prononciation":"", "translation":" pigeon", "type": "nom", "family":"hiragana",  "level":2},
{ "myId":139, "name": "咲きます", "prononciation":" Sakimasu", "translation":"fleurir", "type": "vb", "family":"kanji",  "level":2},
{ "myId":140, "name": "水", "prononciation":"mizu", "translation":"eau", "type": "nom", "family":"kanji",  "level":2},
{ "myId":141, "name": "何", "prononciation":"nani", "translation":"Quoi", "type": "adv", "family":"kanji",  "level":2},
{ "myId":142, "name": "分", "prononciation":"pun/bun/fun", "translation":"Minute", "type": "nom", "family":"kanji",  "level":2},
{ "myId":143, "name": "午", "prononciation":"go", "translation":"midi", "type": "adv", "family":"kanji",  "level":2},
{ "myId":144, "name": "後", "prononciation":"ato/go", "translation":"Après", "type": "adv", "family":"kanji",  "level":2},
{ "myId":145, "name": "台所", "prononciation":"daidokoro", "translation":"Cuisiner", "type": "nom", "family":"kanji",  "level":3},
{ "myId":146, "name": "部屋", "prononciation":"hea", "translation":"Chambre/pièce", "type": "nom", "family":"kanji",  "level":3},
{ "myId":147, "name": "風呂", "prononciation":"furu", "translation":"Salle de bain", "type": "nom", "family":"kanji",  "level":3},
{ "myId":148, "name": "庭", "prononciation":"niwa", "translation":"jardin", "type": "nom", "family":"kanji",  "level":3},
{ "myId":149, "name": "家", "prononciation":"ie/uchi", "translation":"Maison", "type": "nom", "family":"kanji",  "level":3},
{ "myId":150, "name": "窓", "prononciation":"mado", "translation":"Fenêtre", "type": "nom", "family":"kanji",  "level":3},
{ "myId":151, "name": "猫", "prononciation":"neko", "translation":"chat", "type": "nom", "family":"kanji",  "level":3},
{ "myId":152, "name": "高い ", "prononciation":"takai", "translation":"Cher", "type": "adj", "family":"kanji",  "level":3},
{ "myId":153, "name": "大阪", "prononciation":"Osaka", "translation":"Osaka", "type": "nom", "family":"kanji",  "level":3},
{ "myId":154, "name": "近い", "prononciation":"chikai", "translation":"proche", "type": "adj", "family":"kanji",  "level":3},
{ "myId":155, "name": "駅", "prononciation":"eki", "translation":"gare", "type": "nom", "family":"kanji",  "level":3},
{ "myId":156, "name": "遠い", "prononciation":"tooi", "translation":"loin", "type": "adj", "family":"kanji",  "level":3},
{ "myId":157, "name": "速い", "prononciation":"hayai", "translation":"rapide", "type": "adj", "family":"kanji",  "level":3},
{ "myId":158, "name": "歩きます", "prononciation":"arukimasu", "translation":"marcher", "type": "vb", "family":"kanji",  "level":3},
{ "myId":159, "name": "黄色", "prononciation":"kiiro", "translation":"jaune", "type": "adj", "family":"kanji",  "level":3},
{ "myId":160, "name": "赤い", "prononciation":"akai", "translation":"rouge", "type": "adj", "family":"kanji",  "level":3},
{ "myId":161, "name": "春", "prononciation":"haru", "translation":"printemps", "type": "nom", "family":"kanji",  "level":3},
{ "myId":162, "name": "秋", "prononciation":"aki", "translation":"automne", "type": "nom", "family":"kanji",  "level":3},
{ "myId":163, "name": "夏", "prononciation":"Natsu", "translation":"été", "type": "nom", "family":"kanji",  "level":3},
{ "myId":164, "name": "冬", "prononciation":"fuyu", "translation":"hiver", "type": "nom", "family":"kanji",  "level":3},
{ "myId":165, "name": "公園", "prononciation":"Kouen", "translation":"Parc/jardin ", "type": "nom", "family":"kanji",  "level":3},
{ "myId":166, "name": "散歩", "prononciation":"Sanppo", "translation":" promener", "type": "vb", "family":"kanji",  "level":3},
{ "myId":167, "name": "映画館", "prononciation":"Eigakan", "translation":"cinema", "type": "nom", "family":"kanji",  "level":3},
{ "myId":168, "name": "泳ぎま", "prononciation":"Oyogimasu", "translation":"Nager", "type": "vb", "family":"kanji",  "level":3},
{ "myId":169, "name": "忙しい", "prononciation":"Isogashii", "translation":"occupé", "type": "adj", "family":"kanji",  "level":3},
{ "myId":170, "name": "かけます", "prononciation":"", "translation":"Décrocher (telephone)", "type": "vb", "family":"kanji",  "level":3},
{ "myId":171, "name": "練習", "prononciation":"renshuu", "translation":"Sentrainer", "type": "vb", "family":"kanji",  "level":3},
{ "myId":172, "name": "ピアノ", "prononciation":"", "translation":"Piano", "type": "nom", "family":"katakana",  "level":3},
{ "myId":173, "name": "作りま", "prononciation":"Tsukurimasu", "translation":"Construire/ fait", "type": "vb", "family":"kanji",  "level":3},
{ "myId":174, "name": "スポーツ", "prononciation":"", "translation":"Sport", "type": "nom", "family":"katakana",  "level":3},
{ "myId":175, "name": "韓国", "prononciation":" Kankokku", "translation":" Corée du Sud", "type": "nom", "family":"kanji",  "level":3},
{ "myId":176, "name": "読みま", "prononciation":" Yomimasu", "translation":"lire", "type": "vb", "family":"kanji",  "level":3},
{ "myId":177, "name": "番号", "prononciation":" Bangou", "translation":"  Numéro", "type": "nom", "family":"kanji",  "level":3},
{ "myId":178, "name": "弱い", "prononciation":"yowai", "translation":"  faible", "type": "adj", "family":"kanji",  "level":3},
{ "myId":179, "name": "吹kiます", "prononciation":"fukimasu", "translation":"souffler", "type": "vb", "family":"kanji",  "level":3},
{ "myId":180, "name": "晴れ", "prononciation":" Hare", "translation":"ensolleilé", "type": "adj", "family":"kanji",  "level":3},
{ "myId":181, "name": "降る", "prononciation":"furu", "translation":"Pleuvoir", "type": "vb", "family":"kanji",  "level":3},
{ "myId":182, "name": "雨", "prononciation":"Ame", "translation":"Pluit", "type": "nom", "family":"kanji",  "level":3},
{ "myId":183, "name": "空", "prononciation":"Sora", "translation":"Ciel", "type": "nom", "family":"kanji",  "level":3},
{ "myId":184, "name": "雪", "prononciation":"Yuki", "translation":"neige", "type": "nom", "family":"kanji",  "level":3},
{ "myId":185, "name": "外", "prononciation":"Soto ", "translation":"dehors", "type": "nom", "family":"kanji",  "level":3},
{ "myId":186, "name": "朝", "prononciation":"Asa", "translation":"matin", "type": "nom", "family":"kanji",  "level":3},
{ "myId":187, "name": "今晩", "prononciation":"Konban", "translation":"Ce soir", "type": "nom", "family":"kanji",  "level":3},
{ "myId":188, "name": "寒い", "prononciation":"samui", "translation":"froid", "type": "adj", "family":"kanji",  "level":3},
{ "myId":189, "name": "吹いている", "prononciation":"Fuyite imasu", "translation":"Est en train de souffler", "type": "vb", "family":"kanji",  "level":3},
{ "myId":190, "name": "涼しい", "prononciation":"Suzushii", "translation":"frais", "type": "adj", "family":"kanji",  "level":3},
{ "myId":191, "name": "全然", "prononciation":"zenzen", "translation":"Pas du tout", "type": "adv", "family":"kanji",  "level":3},
{ "myId":192, "name": "野菜", "prononciation":"Yasai", "translation":"legumes", "type": "nom", "family":"kanji",  "level":3},
{ "myId":193, "name": "大変", "prononciation":"taihen", "translation":"Beaucoup (vraiment beaucoup)", "type": "adj", "family":"kanji",  "level":3},
{ "myId":194, "name": "ラーメン", "prononciation":"", "translation":"Ramen", "type": "nom", "family":"katakana",  "level":3},
{ "myId":195, "name": "少ない", "prononciation":"sukunai", "translation":"Pas assez", "type": "adv", "family":"kanji",  "level":3},
{ "myId":196, "name": "お弁当", "prononciation":"Obento", "translation":" Bentô", "type": "nom", "family":"kanji",  "level":3},
{ "myId":197, "name": "塩", "prononciation":"Shio", "translation":"sel", "type": "nom", "family":"kanji",  "level":3},
{ "myId":198, "name": "ご飯", "prononciation":"Gohan", "translation":"riz", "type": "nom", "family":"kanji",  "level":3},
{ "myId":199, "name": "砂糖", "prononciation":"Satou", "translation":"sucre", "type": "nom", "family":"kanji",  "level":3},
{ "myId":200, "name": "全部", "prononciation":"Zenbu", "translation":"tout", "type": "adv", "family":"kanji",  "level":3},
{ "myId":201, "name": "牛乳", "prononciation":"Gyuunyu", "translation":"Lait", "type": "nom", "family":"kanji",  "level":3},
{ "myId":202, "name": "毎朝", "prononciation":"Maiasa", "translation":"Chaque matin", "type": "adv", "family":"kanji",  "level":3},
{ "myId":203, "name": "洗いま", "prononciation":"haraimasu", "translation":"laver", "type": "vb", "family":"kanji",  "level":3},
{ "myId":204, "name": "スプーン", "prononciation":"", "translation":"cuillère", "type": "nom", "family":"katakana",  "level":3},
{ "myId":205, "name": "ボウル", "prononciation":"", "translation":"bol", "type": "nom", "family":"katakana",  "level":3},
{ "myId":206, "name": "カレー", "prononciation":"", "translation":"curry", "type": "nom", "family":"katakana",  "level":3},
{ "myId":207, "name": "本当Ni", "prononciation":"Hontouni", "translation":"vraiment", "type": "adv", "family":"kanji",  "level":3},
{ "myId":208, "name": "すっぱい", "prononciation":"", "translation":"acide", "type": "nom", "family":"kanji",  "level":3},
{ "myId":209, "name": "塩っぱい", "prononciation":"Chouppai", "translation":"salé", "type": "nom", "family":"kanji",  "level":3},
{ "myId":210, "name": "お箸", "prononciation":"Ohashi", "translation":"baguettes", "type": "nom", "family":"kanji",  "level":3},
{ "myId":211, "name": "茶碗", "prononciation":"Chawan", "translation":"Bol de riz", "type": "nom", "family":"kanji",  "level":3},
{ "myId":212, "name": "広い ", "prononciation":"hiroi", "translation":"Large/spacieux/gros", "type": "nom", "family":"kanji",  "level":3},
{ "myId":213, "name": "病院", "prononciation":"Byouin", "translation":" hopital", "type": "nom", "family":"kanji",  "level":3},
{ "myId":214, "name": "出身", "prononciation":"Shuushin", "translation":"Lieu de naissance", "type": "nom", "family":"kanji",  "level":3},
{ "myId":215, "name": "出口", "prononciation":"Deguchi", "translation":" sortie", "type": "nom", "family":"kanji",  "level":3},
{ "myId":216, "name": "銀行", "prononciation":"Ginkou", "translation":"banque", "type": "nom", "family":"kanji",  "level":4},
{ "myId":217, "name": "長い", "prononciation":"Nagai", "translation":"Long", "type": "adj", "family":"kanji",  "level":4},
{ "myId":218, "name": "店", "prononciation":"Mise", "translation":"magasin", "type": "nom", "family":"kanji",  "level":4},
{ "myId":219, "name": "東", "prononciation":"Higashi", "translation":"est", "type": "nom", "family":"kanji",  "level":4},
{ "myId":220, "name": "西", "prononciation":" nishi", "translation":"  ouest", "type": "nom", "family":"kanji",  "level":4},
{ "myId":221, "name": "南", "prononciation":"Minami", "translation":" Sud", "type": "nom", "family":"kanji",  "level":4},
{ "myId":222, "name": "北", "prononciation":" Kita", "translation":" nord", "type": "nom", "family":"kanji",  "level":4},
{ "myId":223, "name": "北東", "prononciation":"Hokkutou", "translation":"Nord-est", "type": "nom", "family":"kanji",  "level":2},
{ "myId":224, "name": "通ります", "prononciation":"Tourimasu", "translation":"Passer(par)", "type": "vb", "family":"kanji",  "level":4},
{ "myId":225, "name": "入ります", "prononciation":"Hairimasu", "translation":"rentrer", "type": "vb", "family":"kanji",  "level":4},
{ "myId":226, "name": "次", "prononciation":"Tsugi", "translation":"prochain", "type": "nom", "family":"kanji",  "level":4},
{ "myId":227, "name": "進みま", "prononciation":"Susumimasu", "translation":"avancer", "type": "vb", "family":"kanji",  "level":4},
{ "myId":228, "name": "", "prononciation":"まっすぐ", "translation":"Tout droit", "type": "adv", "family":"kanji",  "level":4},
{ "myId":229, "name": "曲がります", "prononciation":"Magarimasu", "translation":"tourner", "type": "vb", "family":"kanji",  "level":4},
{ "myId":230, "name": "今年", "prononciation":"Kotoshi", "translation":"Cette année", "type": "adv", "family":"kanji",  "level":4},
{ "myId":231, "name": "誕生日", "prononciation":"Tanjoubi", "translation":"Anniversaire", "type": "nom", "family":"kanji",  "level":4},
{ "myId":232, "name": "お金", "prononciation":"Okane", "translation":"argent", "type": "nom", "family":"kanji",  "level":4},
{ "myId":233, "name": "時計", "prononciation":"Toke", "translation":" horloge", "type": "nom", "family":"kanji",  "level":4},
{ "myId":234, "name": "鞄", "prononciation":"Kaban", "translation":" Sac à dos", "type": "nom", "family":"kanji",  "level":4},
{ "myId":235, "name": "腕", "prononciation":"Ude ", "translation":"bras", "type": "nom", "family":"kanji",  "level":4},
{ "myId":236, "name": "出します", "prononciation":"Dashimasu", "translation":"retirer", "type": "vb", "family":"kanji",  "level":4},
{ "myId":237, "name": "もの", "prononciation":"", "translation":" Thing", "type": "nom", "family":"hiragana",  "level":4},
{ "myId":238, "name": "軽い", "prononciation":"Karui", "translation":"léger", "type": "adj", "family":"kanji",  "level":4},
{ "myId":239, "name": "丈夫", "prononciation":"Joubu", "translation":"Solide/durable", "type": "adj", "family":"kanji",  "level":4},
{ "myId":240, "name": "お土産", "prononciation":"Omiyage", "translation":"souvenir(objet)", "type": "nom", "family":"kanji",  "level":4},
{ "myId":241, "name": "もらいました", "prononciation":"moraimasu", "translation":"emprunter", "type": "vb", "family":"hiragana",  "level":4},
{ "myId":242, "name": "大切", "prononciation":"Taisetsu", "translation":"précieux", "type": "adj", "family":"kanji",  "level":4},
{ "myId":243, "name": "違う", "prononciation":"Chigau", "translation":" different", "type": "adv", "family":"kanji",  "level":4},
{ "myId":244, "name": "買い物", "prononciation":"Kaimono", "translation":"shopping", "type": "vb", "family":"kanji",  "level":4},
{ "myId":245, "name": "汚い", "prononciation":"Kitanai", "translation":"dégueulsse", "type": "adj", "family":"kanji",  "level":4},
{ "myId":246, "name": "在宅", "prononciation":"Zaitaku", "translation":"À la maison/chez moi", "type": "adv", "family":"kanji",  "level":4},
{ "myId":247, "name": "立派", "prononciation":" rippa", "translation":" Splendide", "type": "adj", "family":"kanji",  "level":4},
{ "myId":248, "name": "方", "prononciation":" Kata/ hou", "translation":" (cette)personne", "type": "nom", "family":"kanji",  "level":4},
{ "myId":249, "name": "皆さん", "prononciation":" Minna san", "translation":"Tout le monde", "type": "nom", "family":"kanji",  "level":4},
{ "myId":250, "name": "離婚", "prononciation":"rikkon", "translation":" divorcer", "type": "vb", "family":"kanji",  "level":4},
{ "myId":251, "name": "結婚", "prononciation":" Kekkon", "translation":" Se marier", "type": "vb", "family":"kanji",  "level":4},
{ "myId":252, "name": "別れます", "prononciation":" Wakaremasu", "translation":"  rompre", "type": "vb", "family":"kanji",  "level":4},
{ "myId":253, "name": "赤ちゃん", "prononciation":"Akachan", "translation":"Bébé", "type": "nom", "family":"kanji",  "level":4},
{ "myId":254, "name": "呼びます", "prononciation":"Youbimasu", "translation":"Appeler", "type": "vb", "family":"kanji",  "level":4},
{ "myId":255, "name": "洗濯", "prononciation":"Sentaku", "translation":"faire la lessive", "type": "vb", "family":"kanji",  "level":4},
{ "myId":256, "name": "シャワー", "prononciation":"shawa", "translation":"douche", "type": "nom", "family":"kanji",  "level":4},
{ "myId":257, "name": "手紙", "prononciation":"Tegami", "translation":"lettre", "type": "nom", "family":"kanji",  "level":4},
{ "myId":258, "name": "開けます", "prononciation":" Akemasu", "translation":" ouvrir", "type": "vb", "family":"kanji",  "level":4},
{ "myId":259, "name": "立って", "prononciation":"Tatte", "translation":"debout", "type": "vb", "family":"kanji",  "level":4},
{ "myId":260, "name": "立ちます", "prononciation":"Tachimasu", "translation":"Se lever", "type": "vb", "family":"kanji",  "level":4},
{ "myId":261, "name": "つけmasu", "prononciation":"tsukemasu", "translation":"Allumer", "type": "vb", "family":"hiragana",  "level":4},
{ "myId":262, "name": "紅茶", "prononciation":"Kocha", "translation":"Thé noir", "type": "nom", "family":"kanji",  "level":4},
{ "myId":263, "name": "起きまSu", "prononciation":"Okimasu", "translation":" Se réveiller", "type": "vb", "family":"kanji",  "level":4},
{ "myId":264, "name": "ドア", "prononciation":"Doa", "translation":"door", "type": "nom", "family":"katakana",  "level":4},
{ "myId":265, "name": "始まります", "prononciation":"hajimemasu", "translation":" commencer", "type": "vb", "family":"kanji",  "level":4},
{ "myId":266, "name": "宿題", "prononciation":"Shikudai", "translation":" devoirs", "type": "nom", "family":"kanji",  "level":4},
{ "myId":267, "name": "終わりま", "prononciation":"Owarimasu", "translation":" Finir", "type": "vb", "family":"kanji",  "level":4},
{ "myId":268, "name": "テスト", "prononciation":"tesuto", "translation":"Examen", "type": "nom", "family":"katakana",  "level":4},
{ "myId":269, "name": "難しI", "prononciation":" Muzukashi", "translation":" Difficile", "type": "adj", "family":"kanji",  "level":4},
{ "myId":270, "name": "覚えます", "prononciation":"Oboemasu", "translation":"Mémorise/Se souvenir", "type": "vb", "family":"kanji",  "level":4},
{ "myId":271, "name": "言葉", "prononciation":" Kotoba", "translation":" Mots", "type": "nom", "family":"kanji",  "level":4},
{ "myId":272, "name": "教えmasu", "prononciation":"oshiemasu", "translation":"Montrer/dire", "type": "vb", "family":"kanji",  "level":4},
{ "myId":273, "name": "花瓶", "prononciation":"Kabin", "translation":" vase", "type": "nom", "family":"kanji",  "level":4},
{ "myId":274, "name": "登ります", "prononciation":"Noborimasu", "translation":" grimper", "type": "vb", "family":"kanji",  "level":4},
{ "myId":275, "name": "川", "prononciation":" Kawa", "translation":" riviere", "type": "nom", "family":"kanji",  "level":4},
{ "myId":276, "name": "声", "prononciation":" Koe", "translation":"  voix", "type": "nom", "family":"kanji",  "level":4},
{ "myId":277, "name": "賑やか", "prononciation":"Nigiyaka", "translation":" Animé/blindé", "type": "nom", "family":"kanji",  "level":4},
{ "myId":278, "name": "さる", "prononciation":"saru", "translation":" singe", "type": "nom", "family":"hiragana",  "level":4},
{ "myId":279, "name": "動物", "prononciation":"Doubutsu", "translation":" animaux", "type": "nom", "family":"kanji",  "level":4},
{ "myId":280, "name": "飛びます", "prononciation":"Tobimasu", "translation":"S'envoler", "type": "vb", "family":"kanji",  "level":4},
{ "myId":281, "name": "お兄さん ", "prononciation":"oniisan", "translation":"grand frere (polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":282, "name": "お姉さん ", "prononciation":"oneesan", "translation":"grande sœur (polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":283, "name": "弟さん ", "prononciation":"otoutosan", "translation":"petit frere (polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":284, "name": "お子さん ", "prononciation":"okosan", "translation":"enfant (fils/fille - polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":285, "name": "ご両親 ", "prononciation":"gorioushin", "translation":"parents (polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":286, "name": "お父さん ", "prononciation":"otousan", "translation":"père (polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":287, "name": "お祖母さん ", "prononciation":"obaasan", "translation":"grand-mère (polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":288, "name": "お母さん ", "prononciation":"okaasan", "translation":"mère (polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":289, "name": "お祖父さん ", "prononciation":"ojiisan", "translation":"grand-père (polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":290, "name": "妹さん ", "prononciation":"imoutosan", "translation":"petite-sœur (polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":291, "name": "兄", "prononciation":"ani", "translation":"grand-frère", "type": "nom", "family":"kanji",  "level":5},
{ "myId":292, "name": "伯父 ", "prononciation":"oji ", "translation":"oncle plus vieux que parent", "type": "nom", "family":"kanji",  "level":5},
{ "myId":293, "name": "姉 ", "prononciation":"anee", "translation":"grande sœur ", "type": "nom", "family":"kanji",  "level":5},
{ "myId":294, "name": "伯母 ", "prononciation":"obaaa", "translation":"tante plus vieux que parent", "type": "nom", "family":"kanji",  "level":5},
{ "myId":295, "name": "弟 ", "prononciation":"otouto", "translation":"petit frère ", "type": "nom", "family":"kanji",  "level":5},
{ "myId":296, "name": "叔父 ", "prononciation":"oji", "translation":"oncle plus jeune que parent", "type": "nom", "family":"kanji",  "level":5},
{ "myId":297, "name": "妹 ", "prononciation":"imouto", "translation":"petite sœur", "type": "nom", "family":"kanji",  "level":5},
{ "myId":298, "name": "叔母 ", "prononciation":"oba", "translation":"tante plus jeune que parent", "type": "nom", "family":"kanji",  "level":5},
{ "myId":299, "name": "子供 ", "prononciation":"kodomo", "translation":"enfant (fils/fille) ", "type": "nom", "family":"kanji",  "level":5},
{ "myId":300, "name": "夫 ", "prononciation":"otto", "translation":"mari", "type": "nom", "family":"kanji",  "level":5},
{ "myId":301, "name": "両親 ", "prononciation":"rioushin", "translation":"parents", "type": "nom", "family":"kanji",  "level":5},
{ "myId":302, "name": "妻 ", "prononciation":"tsuma", "translation":"femme", "type": "nom", "family":"kanji",  "level":5},
{ "myId":303, "name": "父 ", "prononciation":"chichi", "translation":"père", "type": "nom", "family":"kanji",  "level":5},
{ "myId":304, "name": "母 ", "prononciation":"haha", "translation":"mère", "type": "nom", "family":"kanji",  "level":5},
{ "myId":305, "name": "伯父さん ", "prononciation":"ojisan", "translation":"oncle plus vieux que parent (polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":306, "name": "伯母さん ", "prononciation":"obasan", "translation":"tante plus vieux que parent (polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":307, "name": "叔父さん", "prononciation":"ojisan", "translation":"oncle plus jeune que parent (polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":308, "name": "叔母さん ", "prononciation":"obasan", "translation":"tante plus jeune que parent (polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":309, "name": "ご主人 ", "prononciation":"goshujin", "translation":"mari (polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":310, "name": "奥さん", "prononciation":"okusan", "translation":"femme (mariée - polie)", "type": "nom", "family":"kanji",  "level":5},
{ "myId":311, "name": "天気", "prononciation":"tenki", "translation":"meteo", "type": "nom", "family":"kanji",  "level":5},
{ "myId":312, "name": "元気", "prononciation":"genki", "translation":"aller bien", "type": "nom", "family":"kanji",  "level":5},
{ "myId":313, "name": "円", "prononciation":"en/yen", "translation":"yen (arrrrrgent)", "type": "adv", "family":"kanji",  "level":5},
{ "myId":314, "name": "", "prononciation":"いってきます", "translation":"Je sors !", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":315, "name": "", "prononciation":"いってらっしゃい", "translation":"Prends soin de toi!", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":316, "name": "", "prononciation":"ただいま", "translation":"Je suis rentré!", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":317, "name": "", "prononciation":"おかえりなさい", "translation":"Bon retour à la maison", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":318, "name": "", "prononciation":"あまり ", "translation":"pas trop", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":319, "name": "", "prononciation":"ほか ", "translation":"autre", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":320, "name": "", "prononciation":"おいくつ ", "translation":"combien, quel age", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":321, "name": "", "prononciation":"じゃあ ", "translation":"bon...", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":322, "name": "親", "prononciation":"oya", "translation":"parent", "type": "nom", "family":"kanji",  "level":5},
{ "myId":323, "name": "似ています ", "prononciation":"niています ", "translation":"ressembler", "type": "vb", "family":"kanji",  "level":5},
{ "myId":324, "name": "", "prononciation":"から ", "translation":"depuis", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":325, "name": "", "prononciation":"まで ", "translation":"jusqu'à", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":326, "name": "", "prononciation":"タクシー", "translation":"taxi", "type": "nom", "family":"katakana",  "level":5},
{ "myId":327, "name": "", "prononciation":"かかります ", "translation":"prendre (en temps)", "type": "vb", "family":"hiragana",  "level":5},
{ "myId":328, "name": "", "prononciation":"ホテル ", "translation":"hôtel", "type": "nom", "family":"katakana",  "level":5},
{ "myId":329, "name": "", "prononciation":"セータ ", "translation":"sweat ( à capuche par ex)", "type": "nom", "family":"katakana",  "level":5},
{ "myId":330, "name": "", "prononciation":"gurai", "translation":"environ", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":331, "name": "", "prononciation":"バス ", "translation":"bus", "type": "nom", "family":"katakana",  "level":5},
{ "myId":332, "name": "", "prononciation":"ジュース ", "translation":"jus", "type": "nom", "family":"katakana",  "level":5},
{ "myId":333, "name": "", "prononciation":"よく ", "translation":"souvent", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":334, "name": "", "prononciation":"スカート", "translation":"jupe", "type": "nom", "family":"katakana",  "level":5},
{ "myId":335, "name": "", "prononciation":"パンツ", "translation":"culotte/calecon", "type": "nom", "family":"katakana",  "level":5},
{ "myId":336, "name": "", "prononciation":"ズボン", "translation":"pantalon", "type": "nom", "family":"katakana",  "level":5},
{ "myId":337, "name": "", "prononciation":"さあ ", "translation":"j'en suis pas sur, allez", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":338, "name": "", "prononciation":"たくさん ", "translation":"beaucoup (en comptant)", "type": "adj", "family":"hiragana",  "level":5},
{ "myId":339, "name": "", "prononciation":"また ", "translation":"encore", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":340, "name": "", "prononciation":"どちら ", "translation":"où, lequel", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":341, "name": "", "prononciation":"どうやって ", "translation":"comment", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":342, "name": "", "prononciation":"どうぞ ", "translation":"je t'en prie", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":343, "name": "", "prononciation":"あなたにとって ", "translation":"Pour toi", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":344, "name": "", "prononciation":"Sorekara ", "translation":"ensuite", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":345, "name": "", "prononciation":"すぐに ", "translation":"immédiatement", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":346, "name": "", "prononciation":"しかし ", "translation":"mais", "type": "adv", "family":"hiragana",  "level":5},
{ "myId":347, "name": "他", "prononciation":"hoka", "translation":"autre", "type": "adv", "family":"kanji",  "level":5},
{ "myId":348, "name": "彼ら", "prononciation":"karera", "translation":"ils", "type": "adv", "family":"kanji",  "level":5},
{ "myId":349, "name": "もう直ぐ", "prononciation":"mousugu", "translation":"sur le point de…", "type": "adv", "family":"kanji",  "level":5},
{ "myId":350, "name": "半分", "prononciation":"hanbun", "translation":"moitié", "type": "adv", "family":"kanji",  "level":5},
{ "myId":351, "name": "海", "prononciation":"うみ", "translation":"mer", "type": "", "family":"kanji",  "level":6},
{ "myId":352, "name": "先月", "prononciation":"らいげつ", "translation":"le mois dernier", "type": "", "family":"kanji",  "level":6},
{ "myId":353, "name": "来月", "prononciation":"らいげつ", "translation":"le prochain mois", "type": "", "family":"kanji",  "level":6},
{ "myId":354, "name": "再来週", "prononciation":"さらいしゅう", "translation":"Dans 2 semaines", "type": "", "family":"kanji",  "level":6},
{ "myId":355, "name": "被ります", "prononciation":"かぶります", "translation":"porter (tête)", "type": "", "family":"kanji",  "level":6},
{ "myId":356, "name": "鉛筆", "prononciation":"enpitsu", "translation":"stylo", "type": "", "family":"kanji",  "level":6},
{ "myId":357, "name": "答ます", "prononciation":"kotaemasu", "translation":"répondre", "type": "", "family":"kanji",  "level":6},
{ "myId":358, "name": "簡単", "prononciation":"kantan", "translation":"facile, simple", "type": "", "family":"kanji",  "level":6},
{ "myId":359, "name": "", "prononciation":"クラス", "translation":"classe", "type": "", "family":"",  "level":6},
{ "myId":360, "name": "質問", "prononciation":"shitsumon", "translation":"demander(question),  question", "type": "", "family":"kanji",  "level":6},
{ "myId":361, "name": "知って", "prononciation":"", "translation":"", "type": "", "family":"kanji",  "level":6},
{ "myId":362, "name": "問題", "prononciation":"mondai", "translation":"question, problème", "type": "", "family":"kanji",  "level":6},
{ "myId":363, "name": "言います", "prononciation":"iimasu", "translation":"dire", "type": "", "family":"kanji",  "level":6},
{ "myId":364, "name": "袋", "prononciation":"fukurou", "translation":"sac", "type": "", "family":"kanji",  "level":6},
{ "myId":365, "name": "", "prononciation":"ペン", "translation":"crayon", "type": "", "family":"",  "level":6},
{ "myId":366, "name": "温めます", "prononciation":"atatamemasu", "translation":"chauffer", "type": "", "family":"kanji",  "level":6},
{ "myId":367, "name": "傘", "prononciation":"kasa", "translation":"parapluit", "type": "", "family":"kanji",  "level":6},
{ "myId":368, "name": "教室", "prononciation":"kyoushitsu", "translation":"classe (salle)", "type": "", "family":"kanji",  "level":6},
{ "myId":369, "name": "静か", "prononciation":"shizuka", "translation":"silencieux, calme", "type": "", "family":"kanji",  "level":6},
{ "myId":370, "name": "飛んでいます", "prononciation":"tonde imasu", "translation":"en train de voler", "type": "", "family":"kanji",  "level":6},
{ "myId":371, "name": "", "prononciation":"レシート", "translation":"reçu", "type": "", "family":"",  "level":6},
{ "myId":372, "name": "", "prononciation":"おにぎり", "translation":"onigiri", "type": "", "family":"",  "level":6},
{ "myId":373, "name": "店内", "prononciation":"tenai", "translation":"magasin", "type": "", "family":"kanji",  "level":6},
{ "myId":374, "name": "少々", "prononciation":"shoushou", "translation":"brêvement", "type": "", "family":"kanji",  "level":6},
{ "myId":375, "name": "唐揚げ", "prononciation":"karaage", "translation":"poulet frits ", "type": "", "family":"kanji",  "level":6},
{ "myId":376, "name": "", "prononciation":"うるさい", "translation":"bruyant", "type": "", "family":"",  "level":6},
{ "myId":377, "name": "門mon", "translation":"portail, porte", "type": "", "family":"kanji",  "level":6},
{ "myId":378, "name": "町machi", "translation":"ville", "type": "", "family":"kanji",  "level":6},
{ "myId":379, "name": "自動車", "prononciation":"jidousha", "translation":"automobile", "type": "", "family":"kanji",  "level":6},
{ "myId":380, "name": "図書館", "prononciation":"toshoukan", "translation":"librairie", "type": "", "family":"kanji",  "level":6},
{ "myId":381, "name": "冊", "prononciation":"satsu", "translation":"particule compteur livre", "type": "", "family":"kanji",  "level":6},
{ "myId":382, "name": "運転手", "prononciation":"Untenshi", "translation":"chauffeur", "type": "", "family":"kanji",  "level":6},
{ "myId":383, "name": "階段", "prononciation":"kaidan", "translation":"escalier", "type": "", "family":"kanji",  "level":6},
{ "myId":384, "name": "止まります", "prononciation":"tomarimasu", "translation":"s'arrêter", "type": "", "family":"kanji",  "level":6},
{ "myId":385, "name": "村", "prononciation":"mura", "translation":"village", "type": "", "family":"kanji",  "level":6},
{ "myId":386, "name": "住んでいます", "prononciation":"sunde imasu", "translation":"vivre (qqpart)", "type": "", "family":"kanji",  "level":6},
{ "myId":387, "name": "橋", "prononciation":"hashi", "translation":"pont", "type": "", "family":"kanji",  "level":6},
{ "myId":388, "name": "戸", "prononciation":"tou", "translation":"porte coulissante", "type": "", "family":"kanji",  "level":6},
{ "myId":389, "name": "何でも", "prononciation":"nandemo", "translation":"tout", "type": "", "family":"kanji",  "level":6},
{ "myId":390, "name": "階", "prononciation":"kai", "translation":"étage", "type": "", "family":"kanji",  "level":6},
{ "myId":391, "name": "切符", "prononciation":"kippu", "translation":"ticket", "type": "", "family":"kanji",  "level":6},
{ "myId":392, "name": "", "prononciation":"メートル", "translation":"mètre", "type": "", "family":"",  "level":6},
{ "myId":393, "name": "嬉しい", "prononciation":"ureshii", "translation":"heureux", "type": "", "family":"kanji",  "level":6},
{ "myId":394, "name": "楽しい", "prononciation":"tanoshii", "translation":"amusant", "type": "", "family":"kanji",  "level":6},
{ "myId":395, "name": "怖い", "prononciation":"kowai", "translation":"peur", "type": "", "family":"kanji",  "level":6},
{ "myId":396, "name": "嫌", "prononciation":"ia", "translation":"ne pas aimer (vers breve)", "type": "", "family":"kanji",  "level":6},
{ "myId":397, "name": "面白い", "prononciation":"omoshiroi", "translation":"intéressant/marrant", "type": "", "family":"kanji",  "level":6},
{ "myId":398, "name": "勉強", "prononciation":"benkyou", "translation":"apprendre", "type": "", "family":"kanji",  "level":6},
{ "myId":399, "name": "仕事", "prononciation":"shigoto", "translation":"métier", "type": "", "family":"kanji",  "level":6},
{ "myId":400, "name": "気分", "prononciation":"kibun", "translation":"humeur", "type": "", "family":"kanji",  "level":6},
{ "myId":401, "name": "気持", "prononciation":"kimochi", "translation":"sensation", "type": "", "family":"kanji",  "level":6},
{ "myId":402, "name": "", "prononciation":"つまらない", "translation":"ennuyeux", "type": "", "family":"kanji6},
{ "myId":403, "name": "疲れます", "prononciation":"tsukamerasu", "translation":"fatigué", "type": "", "family":"kanji6},
{ "myId":404, "name": "親切", "prononciation":"shinsetsu", "translation":"gentil (vers longue)", "type": "", "family":"kanji6},
{ "myId":405, "name": "旅行", "prononciation":"ryouko", "translation":"voyage", "type": "", "family":"kanji6},
{ "myId":406, "name": "暇", "prononciation":"hima", "translation":"libre", "type": "", "family":"kanji6}
]

export default japKanjiData
