 const japKanjiData = [
    { "myId":0, "name": "学生", "prononciation":"gakusei", "translation":"Education", "type": "nom", "family":"kanji",  "level":1},
{ "myId":1, "name": "学生", "prononciation":"gakusei", "translation":"Education", "type": "nom", "family":"kanji",  "level":1},
{ "myId":2, "name": "英語", "prononciation":"eigo", "translation":"Previous", "type": "nom", "family":"kanji",  "level":1},
{ "myId":3, "name": "会社", "prononciation":"kaisha", "translation":"entreprise", "type": "nom", "family":"kanji",  "level":1},
{ "myId":4, "name": "日本", "prononciation":"nihon", "translation":"Japon", "type": "nom", "family":"kanji",  "level":1},
{ "myId":5, "name": "学校", "prononciation":"gakkou", "translation":"Vers l’école", "type": "nom", "family":"kanji",  "level":1},
{ "myId":6, "name": "時", "prononciation":"toki/ji", "translation":"Heure", "type": "adv", "family":"kanji",  "level":1},
{ "myId":7, "name": "今", "prononciation":"ima/kon", "translation":"Maintenant", "type": "adv", "family":"kanji",  "level":1},
{ "myId":8, "name": "月曜日", "prononciation":"getsuyoubi", "translation":"on Monday", "type": "nom", "family":"kanji",  "level":1},
{ "myId":9, "name": "５月", "prononciation":"5gatsu", "translation":"in May", "type": "nom", "family":"kanji",  "level":1},
{ "myId":10, "name": "２０１６年", "prononciation":"2016nen", "translation":"in 2016", "type": "nom", "family":"kanji",  "level":1},
{ "myId":11, "name": "犬", "prononciation":"inu", "translation":"dog", "type": "nom", "family":"kanji",  "level":1},
{ "myId":12, "name": "鳥", "prononciation":"toru", "translation":"bird", "type": "nom", "family":"kanji",  "level":1},
{ "myId":13, "name": "椅子", "prononciation":"isu", "translation":"chair", "type": "nom", "family":"kanji",  "level":1},
{ "myId":14, "name": "机", "prononciation":"tsukue", "translation":"desk", "type": "nom", "family":"kanji",  "level":1},
{ "myId":15, "name": "百 ", "prononciation":"hiaku", "translation":"one hundred", "type": "adv", "family":"kanji",  "level":1},
{ "myId":16, "name": "千 ", "prononciation":"Sentaku", "translation":"one thousand", "type": "adv", "family":"kanji",  "level":1},
{ "myId":17, "name": "万 ", "prononciation":"man", "translation":"ten thousand", "type": "adv", "family":"kanji",  "level":1},
{ "myId":18, "name": "自転車", "prononciation":"jitensha", "translation":"vélo", "type": "nom", "family":"kanji",  "level":1},
{ "myId":19, "name": "地図", "prononciation":"chiizu", "translation":"carte", "type": "nom", "family":"kanji",  "level":1},
{ "myId":20, "name": "乗ります", "prononciation":"norimasu", "translation":"monter", "type": "vb", "family":"kanji",  "level":1},
{ "myId":21, "name": "新しい", "prononciation":"atarashii", "translation":"nouveau", "type": "adj", "family":"kanji",  "level":1},
{ "myId":22, "name": "着ます", "prononciation":"kimasu", "translation":"Porter(haut)", "type": "vb", "family":"kanji",  "level":1},
{ "myId":23, "name": "履きます", "prononciation":" Hakimasu", "translation":"Porter(bas)", "type": "vb", "family":"kanji",  "level":1},
{ "myId":24, "name": "服", "prononciation":"fuku", "translation":"vêtements", "type": "nom", "family":"kanji",  "level":1},
{ "myId":25, "name": "洗います", "prononciation":"haraimasu", "translation":"Laver", "type": "vb", "family":"kanji",  "level":1},
{ "myId":26, "name": "脱ぎます", "prononciation":"nugimasu", "translation":"Enlever", "type": "vb", "family":"kanji",  "level":1},
{ "myId":27, "name": "茶色", "prononciation":"chairo", "translation":"marron", "type": "adj", "family":"kanji",  "level":1},
{ "myId":28, "name": "黒い", "prononciation":"kuroi", "translation":"Noir", "type": "adj", "family":"kanji",  "level":1},
{ "myId":29, "name": "一緒", "prononciation":"Ishounii", "translation":"Ensemble", "type": "adv", "family":"kanji",  "level":1},
{ "myId":30, "name": "走ります", "prononciation":"Ashirimasu", "translation":"Courir", "type": "vb", "family":"kanji",  "level":1},
{ "myId":31, "name": "来ま", "prononciation":"Kimasu", "translation":"venir", "type": "vb", "family":"kanji",  "level":1},
{ "myId":32, "name": "電話", "prononciation":"Denwa", "translation":"telephone", "type": "nom", "family":"kanji",  "level":1},
{ "myId":33, "name": "ホテル", "prononciation":"", "translation":"hotel", "type": "nom", "family":"katakana",  "level":1},
{ "myId":34, "name": "弾きます", "prononciation":"Hikimasu", "translation":"Jouer(instruments à cordes + piano)", "type": "vb", "family":"kanji",  "level":1},
{ "myId":35, "name": "ギター", "prononciation":"", "translation":"Guitare", "type": "nom", "family":"katakana",  "level":1},
{ "myId":36, "name": "昨日", "prononciation":"Kinou", "translation":"hier", "type": "adv", "family":"kanji",  "level":1},
{ "myId":37, "name": "好き", "prononciation":" Suki", "translation":"Aimer", "type": "vb", "family":"kanji",  "level":1},
{ "myId":38, "name": "料理", "prononciation":" Ryouri", "translation":"Cuisiner", "type": "vb", "family":"kanji",  "level":1},
{ "myId":39, "name": "パソコン", "prononciation":"", "translation":"PC", "type": "nom", "family":"katakana",  "level":1},
{ "myId":40, "name": "新聞", "prononciation":"Shinbun", "translation":"journal", "type": "nom", "family":"kanji",  "level":1},
{ "myId":41, "name": "大丈夫", "prononciation":"Daijoubu", "translation":" Ca va/non merci", "type": "int", "family":"kanji",  "level":1},
{ "myId":42, "name": "強い", "prononciation":"tsuyoi", "translation":"fort", "type": "adj", "family":"kanji",  "level":1},
{ "myId":43, "name": "風", "prononciation":"Kaze", "translation":"vent", "type": "nom", "family":"kanji",  "level":1},
{ "myId":44, "name": "悪い", "prononciation":"warui", "translation":"mauvais", "type": "adj", "family":"kanji",  "level":1},
{ "myId":45, "name": "昨日", "prononciation":"Kinou", "translation":"hier", "type": "adv", "family":"kanji",  "level":1},
{ "myId":46, "name": "曇り", "prononciation":"Kumori", "translation":"Nuageux", "type": "adj", "family":"kanji",  "level":1},
{ "myId":47, "name": "降ります", "prononciation":"Furimasu", "translation":"Pleuvoir", "type": "vb", "family":"kanji",  "level":1},
{ "myId":48, "name": "大きい", "prononciation":"Ookii", "translation":"grand", "type": "adj", "family":"kanji",  "level":1},
{ "myId":49, "name": "夕べ", "prononciation":"Yube", "translation":"Last night", "type": "adv", "family":"kanji",  "level":1},
{ "myId":50, "name": "今朝", "prononciation":"Kesa", "translation":"Ce matin", "type": "adv", "family":"kanji",  "level":1},
{ "myId":51, "name": "明るい", "prononciation":"Akarui", "translation":"bright", "type": "adj", "family":"kanji",  "level":1},
{ "myId":52, "name": "暗い", "prononciation":"Kurai", "translation":"sombre", "type": "adj", "family":"kanji",  "level":1},
{ "myId":53, "name": "会いまsu", "prononciation":"Aimasu", "translation":"rencontrer", "type": "vb", "family":"kanji",  "level":1},
{ "myId":54, "name": "暑い", "prononciation":"Atsui", "translation":"Chaud(hot)", "type": "adj", "family":"kanji",  "level":1},
{ "myId":55, "name": "暖かい", "prononciation":"Attakai", "translation":"Chaud(warm)", "type": "adj", "family":"kanji",  "level":1},
{ "myId":56, "name": "全く", "prononciation":"mattaku", "translation":"Pas du tout", "type": "adv", "family":"hiragana",  "level":1},
{ "myId":57, "name": "とても", "prononciation":"", "translation":"Beaucoup", "type": "adv", "family":"hiragana",  "level":1},
{ "myId":58, "name": "おいしい", "prononciation":"", "translation":"délicieux", "type": "adj", "family":"hiragana",  "level":1},
{ "myId":59, "name": "結構 ", "prononciation":"kekkou", "translation":"Assez/quite/non merci", "type": "adv", "family":"kanji",  "level":1},
{ "myId":60, "name": "夕飯", "prononciation":"Yuhan", "translation":"diner", "type": "nom", "family":"kanji",  "level":1},
{ "myId":61, "name": "果物", "prononciation":"Kudamono", "translation":"fruits", "type": "nom", "family":"kanji",  "level":1},
{ "myId":62, "name": "甘い", "prononciation":"Amai", "translation":" Doux/sucré", "type": "adj", "family":"kanji",  "level":1},
{ "myId":63, "name": "多い", "prononciation":"Ooi", "translation":"Beaucoup", "type": "adv", "family":"kanji",  "level":1},
{ "myId":64, "name": "飲み物", "prononciation":"Nomimono", "translation":"boisson", "type": "nom", "family":"kanji",  "level":1},
{ "myId":65, "name": "食べ物", "prononciation":"Tabemono", "translation":"nourriture", "type": "nom", "family":"kanji",  "level":1},
{ "myId":66, "name": "お腹", "prononciation":"Onaka", "translation":"ventre", "type": "nom", "family":"kanji",  "level":1},
{ "myId":67, "name": "使いま", "prononciation":"Tsukaimasu", "translation":"utiliser", "type": "vb", "family":"kanji",  "level":1},
{ "myId":68, "name": "フォーク", "prononciation":"", "translation":"fourchette", "type": "nom", "family":"katakana",  "level":1},
{ "myId":69, "name": "ナイフ", "prononciation":"", "translation":"couteau", "type": "nom", "family":"kanji",  "level":1},
{ "myId":70, "name": "好物", "prononciation":"Koubutsu", "translation":"repas préféré", "type": "nom", "family":"kanji",  "level":1},
{ "myId":71, "name": "本当", "prononciation":"Hontou", "translation":"vérité", "type": "adv", "family":"kanji",  "level":1},
{ "myId":72, "name": "ぶどう", "prononciation":"", "translation":"raisin", "type": "nom", "family":"hiragana",  "level":1},
{ "myId":73, "name": "スープ", "prononciation":"", "translation":"soupe", "type": "nom", "family":"katakana",  "level":1},
{ "myId":74, "name": "ワイン", "prononciation":"", "translation":"vin", "type": "nom", "family":"katakana",  "level":1},
{ "myId":75, "name": "寿司", "prononciation":"Sushi", "translation":"sushi", "type": "nom", "family":"kanji",  "level":2},
{ "myId":76, "name": "銀行", "prononciation":" Ginkou", "translation":"banque", "type": "nom", "family":"kanji",  "level":2},
{ "myId":77, "name": "狭い ", "prononciation":"semai", "translation":"Etroi/petit", "type": "adj", "family":"kanji",  "level":2},
{ "myId":78, "name": "建物", "prononciation":"Tatemono", "translation":"batiment", "type": "nom", "family":"kanji",  "level":2},
{ "myId":79, "name": "入り口", "prononciation":"Iriguchi", "translation":"entrée", "type": "nom", "family":"kanji",  "level":2},
{ "myId":80, "name": "", "prononciation":"konbini", "translation":"Convenience store ", "type": "nom", "family":"kanji",  "level":2},
{ "myId":81, "name": "道", "prononciation":"Michi", "translation":"chemin", "type": "nom", "family":"kanji",  "level":2},
{ "myId":82, "name": "向こう", "prononciation":"Mukou", "translation":"Au bout/Là-bas", "type": "adv", "family":"kanji",  "level":2},
{ "myId":83, "name": "出ます", "prononciation":"Demasu", "translation":"quitter", "type": "vb", "family":"kanji",  "level":2},
{ "myId":84, "name": "南", "prononciation":"minami", "translation":" sud", "type": "nom", "family":"kanji",  "level":2},
{ "myId":85, "name": "東", "prononciation":" Higashi", "translation":" est", "type": "nom", "family":"kanji",  "level":2},
{ "myId":86, "name": "北東", "prononciation":"Hokkutou", "translation":"Nord-est", "type": "nom", "family":"kanji",  "level":2},
{ "myId":87, "name": "降ります", "prononciation":"Orimasu", "translation":"Descendre", "type": "vb", "family":"kanji",  "level":2},
{ "myId":88, "name": "通り", "prononciation":"Toori", "translation":"  rue", "type": "nom", "family":"kanji",  "level":2},
{ "myId":89, "name": "はじめに", "prononciation":"", "translation":"first", "type": "adv", "family":"kanji",  "level":2},
{ "myId":90, "name": "角", "prononciation":"Kaku/ kado", "translation":" corner", "type": "nom", "family":"kanji",  "level":2},
{ "myId":91, "name": "出かけます", "prononciation":"Dekakemasu", "translation":"sortir", "type": "vb", "family":"kanji",  "level":2},
{ "myId":92, "name": "年", "prononciation":"Toshi", "translation":"année", "type": "nom", "family":"kanji",  "level":2},
{ "myId":93, "name": "三週間", "prononciation":"San shuukan", "translation":"3 semaines", "type": "adv", "family":"kanji",  "level":2},
{ "myId":94, "name": "毎週月曜日", "prononciation":"Maishuu Getsuyoubi", "translation":"Chaque lundi", "type": "adv", "family":"kanji",  "level":2},
{ "myId":95, "name": "夏休み", "prononciation":"Natsuyasumi", "translation":"Vacances d’été", "type": "nom", "family":"kanji",  "level":2},
{ "myId":96, "name": "お金", "prononciation":"Ohana", "translation":" fleur", "type": "nom", "family":"kanji",  "level":2},
{ "myId":97, "name": "荷物", "prononciation":"nimotsu", "translation":"bagages", "type": "nom", "family":"kanji",  "level":2},
{ "myId":98, "name": "財布", "prononciation":"saifu", "translation":"porte monnaie", "type": "nom", "family":"kanji",  "level":2},
{ "myId":99, "name": "腕時計", "prononciation":"Ude doke", "translation":" montre", "type": "nom", "family":"kanji",  "level":2},
{ "myId":100, "name": "どんな", "prononciation":"", "translation":"Quel (genre de)", "type": "adv", "family":"kanji",  "level":2},
{ "myId":101, "name": "他", "prononciation":"hoka", "translation":"autre", "type": "adv", "family":"kanji",  "level":2},
{ "myId":102, "name": "色々", "prononciation":"Iro iro", "translation":"Toute sorte", "type": "adv", "family":"kanji",  "level":2},
{ "myId":103, "name": "重い", "prononciation":" Omoi", "translation":" lourd", "type": "adj", "family":"kanji",  "level":2},
{ "myId":104, "name": "あげます", "prononciation":"Agemasu", "translation":"donner", "type": "vb", "family":"hiragana",  "level":2},
{ "myId":105, "name": "入れます", "prononciation":"Iremasu", "translation":"Rentrer/mettre dans", "type": "vb", "family":"kanji",  "level":2},
{ "myId":106, "name": "同じ", "prononciation":" Onaji", "translation":" même", "type": "adv", "family":"kanji",  "level":2},
{ "myId":107, "name": "持ちます", "prononciation":"Mochimasu", "translation":"porter", "type": "vb", "family":"kanji",  "level":2},
{ "myId":108, "name": "パン屋", "prononciation":" Panya", "translation":" boulangerie", "type": "nom", "family":"kanji",  "level":2},
{ "myId":109, "name": "売ります", "prononciation":"Urimasu", "translation":" Ne pas avoir besoin", "type": "vb", "family":"kanji",  "level":2},
{ "myId":110, "name": "要ります", "prononciation":" Irimasu", "translation":"Avoir besoin", "type": "vb", "family":"kanji",  "level":2},
{ "myId":111, "name": "土産", "prononciation":"Miyage", "translation":"cadeau", "type": "nom", "family":"kanji",  "level":2},
{ "myId":112, "name": "どなた", "prononciation":"", "translation":" Qui(est-ce)", "type": "adv", "family":"hiragana",  "level":2},
{ "myId":113, "name": "一人", "prononciation":" Hitori", "translation":" seul", "type": "adj", "family":"kanji",  "level":2},
{ "myId":114, "name": "少しい", "prononciation":"Sukoshii", "translation":" Peu", "type": "adv", "family":"kanji",  "level":2},
{ "myId":115, "name": "有名", "prononciation":"Yuume", "translation":"celebre", "type": "adj", "family":"kanji",  "level":2},
{ "myId":116, "name": "彼氏", "prononciation":" Kareshi", "translation":" Copain (amoureux)", "type": "nom", "family":"kanji",  "level":2},
{ "myId":117, "name": "去年", "prononciation":"Kyounen", "translation":"Année dernière", "type": "adv", "family":"kanji",  "level":2},
{ "myId":118, "name": "生まれま", "prononciation":"Umaremasu", "translation":"naitre", "type": "vb", "family":"kanji",  "level":2},
{ "myId":119, "name": "掃除", "prononciation":"Souji", "translation":"Nettoyer", "type": "vb", "family":"kanji",  "level":2},
{ "myId":120, "name": "帰ります", "prononciation":"Kaerimasu", "translation":" Rentrer (à la maison)", "type": "vb", "family":"kanji",  "level":2},
{ "myId":121, "name": "浴びます", "prononciation":"Abimasu", "translation":"Prendre(douche)", "type": "vb", "family":"kanji",  "level":2},
{ "myId":122, "name": "座って", "prononciation":"Suwatte", "translation":"Assis toi", "type": "vb", "family":"kanji",  "level":2},
{ "myId":123, "name": "書いてます", "prononciation":"Kaitemasu", "translation":" Ecrire ", "type": "vb", "family":"kanji",  "level":2},
{ "myId":124, "name": "早い", "prononciation":"Hayai", "translation":"early", "type": "adv", "family":"kanji",  "level":2},
{ "myId":125, "name": "電気", "prononciation":"Denki", "translation":" lumière", "type": "nom", "family":"kanji",  "level":2},
{ "myId":126, "name": "持っています", "prononciation":"Motte imasu", "translation":" Posséder ", "type": "vb", "family":"kanji",  "level":2},
{ "myId":127, "name": "待ちます", "prononciation":"Machimasu", "translation":" Attendre", "type": "vb", "family":"kanji",  "level":2},
{ "myId":128, "name": "出かけます", "prononciation":"Dekakemasu", "translation":" sortir", "type": "vb", "family":"kanji",  "level":2},
{ "myId":129, "name": "ゆっくり", "prononciation":"", "translation":"doucement", "type": "adv", "family":"kanji",  "level":2},
{ "myId":130, "name": "もう", "prononciation":"", "translation":" déjà", "type": "adv", "family":"hiragana",  "level":2},
{ "myId":131, "name": "授業", "prononciation":"Jugyou", "translation":" cours (école)", "type": "nom", "family":"kanji",  "level":2},
{ "myId":132, "name": "易しい", "prononciation":"Yasashii", "translation":" Gentil/facile", "type": "adj", "family":"kanji",  "level":2},
{ "myId":133, "name": "教科書", "prononciation":"kyoukashou", "translation":" Manuel scolaire", "type": "nom", "family":"kanji",  "level":2},
{ "myId":134, "name": "大学", "prononciation":"Daigaku", "translation":" Université", "type": "nom", "family":"kanji",  "level":2},
{ "myId":135, "name": "漢字", "prononciation":"Kanji", "translation":"", "type": "nom", "family":"kanji",  "level":2},
{ "myId":136, "name": "意味", "prononciation":" Imi", "translation":" Sens", "type": "nom", "family":"kanji",  "level":2},
{ "myId":137, "name": "辞書", "prononciation":"jishou", "translation":" dictionnaire", "type": "nom", "family":"kanji",  "level":2},
{ "myId":138, "name": "では", "prononciation":"", "translation":" Durant", "type": "adv", "family":"hiragana",  "level":2},
{ "myId":139, "name": "山", "prononciation":" Yama", "translation":" montagne", "type": "nom", "family":"kanji",  "level":2},
{ "myId":140, "name": "木", "prononciation":" ki", "translation":" arbre", "type": "nom", "family":"kanji",  "level":2},
{ "myId":141, "name": "池", "prononciation":" ike", "translation":"étang", "type": "nom", "family":"kanji",  "level":2},
{ "myId":142, "name": "鳴きます", "prononciation":"Nakimasu", "translation":"Chanter(oiseau)/aboyer", "type": "vb", "family":"kanji",  "level":2},
{ "myId":143, "name": "うるさい", "prononciation":"", "translation":"bruyant", "type": "adj", "family":"hiragana",  "level":2},
{ "myId":144, "name": "はと", "prononciation":"", "translation":" pigeon", "type": "nom", "family":"hiragana",  "level":2},
{ "myId":145, "name": "咲きます", "prononciation":" Sakimasu", "translation":"fleurir", "type": "vb", "family":"kanji",  "level":2},
{ "myId":146, "name": "水", "prononciation":"mizu", "translation":"eau", "type": "nom", "family":"kanji",  "level":2},
{ "myId":147, "name": "何", "prononciation":"nani", "translation":"What", "type": "adv", "family":"kanji",  "level":2},
{ "myId":148, "name": "分", "prononciation":"pun/bun/fun", "translation":"Minute/part", "type": "nom", "family":"kanji",  "level":2},
{ "myId":149, "name": "午", "prononciation":"go", "translation":"Noon", "type": "adv", "family":"kanji",  "level":2},
{ "myId":150, "name": "後", "prononciation":"ato/go", "translation":"After", "type": "adv", "family":"kanji",  "level":2},
{ "myId":151, "name": "台所", "prononciation":"daidokoro", "translation":"kitchen", "type": "nom", "family":"kanji",  "level":3},
{ "myId":152, "name": "部屋", "prononciation":"hea", "translation":"room", "type": "nom", "family":"kanji",  "level":3},
{ "myId":153, "name": "風呂", "prononciation":"furu", "translation":"bath", "type": "nom", "family":"kanji",  "level":3},
{ "myId":154, "name": "庭", "prononciation":"niwa", "translation":"yard/garden", "type": "nom", "family":"kanji",  "level":3},
{ "myId":155, "name": "家", "prononciation":"ie/uchi", "translation":"house", "type": "nom", "family":"kanji",  "level":3},
{ "myId":156, "name": "窓", "prononciation":"mado", "translation":"window", "type": "nom", "family":"kanji",  "level":3},
{ "myId":157, "name": "猫", "prononciation":"neko", "translation":"cat", "type": "nom", "family":"kanji",  "level":3},
{ "myId":158, "name": "高い ", "prononciation":"takai", "translation":"expensive", "type": "adj", "family":"kanji",  "level":3},
{ "myId":159, "name": "大阪", "prononciation":"Osaka", "translation":"Osaka", "type": "nom", "family":"kanji",  "level":3},
{ "myId":160, "name": "近い", "prononciation":"chikai", "translation":"proche", "type": "adj", "family":"kanji",  "level":3},
{ "myId":161, "name": "駅", "prononciation":"eki", "translation":"gare", "type": "nom", "family":"kanji",  "level":3},
{ "myId":162, "name": "遠い", "prononciation":"tooi", "translation":"loin", "type": "adj", "family":"kanji",  "level":3},
{ "myId":163, "name": "速い", "prononciation":"hayai", "translation":"rapide", "type": "adj", "family":"kanji",  "level":3},
{ "myId":164, "name": "歩きます", "prononciation":"arukimasu", "translation":"marcher", "type": "vb", "family":"kanji",  "level":3},
{ "myId":165, "name": "黄色", "prononciation":"kiiro", "translation":"jaune", "type": "adj", "family":"kanji",  "level":3},
{ "myId":166, "name": "赤い", "prononciation":"akai", "translation":"rouge", "type": "adj", "family":"kanji",  "level":3},
{ "myId":167, "name": "春", "prononciation":"haru", "translation":"printemps", "type": "nom", "family":"kanji",  "level":3},
{ "myId":168, "name": "秋", "prononciation":"aki", "translation":"automne", "type": "nom", "family":"kanji",  "level":3},
{ "myId":169, "name": "夏", "prononciation":"Natsu", "translation":"été", "type": "nom", "family":"kanji",  "level":3},
{ "myId":170, "name": "冬", "prononciation":"fuyu", "translation":"hiver", "type": "nom", "family":"kanji",  "level":3},
{ "myId":171, "name": "欲しi", "prononciation":"oshii", "translation":"Vouloir", "type": "vb", "family":"kanji",  "level":3},
{ "myId":172, "name": "公園", "prononciation":"Kouen", "translation":"Parc/jardin ", "type": "nom", "family":"kanji",  "level":3},
{ "myId":173, "name": "散歩", "prononciation":"Sanppo", "translation":" promener", "type": "vb", "family":"kanji",  "level":3},
{ "myId":174, "name": "映画館", "prononciation":"Eigakan", "translation":"cinema", "type": "nom", "family":"kanji",  "level":3},
{ "myId":175, "name": "泳ぎま", "prononciation":"Oyogimasu", "translation":"Nager", "type": "vb", "family":"kanji",  "level":3},
{ "myId":176, "name": "忙しい", "prononciation":"Isogashii", "translation":"occupé", "type": "adj", "family":"kanji",  "level":3},
{ "myId":177, "name": "かけます", "prononciation":"", "translation":"Appeler(telephone)", "type": "vb", "family":"kanji",  "level":3},
{ "myId":178, "name": "教え", "prononciation":"Oshie", "translation":"Montrer", "type": "vb", "family":"kanji",  "level":3},
{ "myId":179, "name": "練習", "prononciation":"renshuu", "translation":"Sentrainer", "type": "vb", "family":"kanji",  "level":3},
{ "myId":180, "name": "ピアノ", "prononciation":"", "translation":"Piano", "type": "nom", "family":"katakana",  "level":3},
{ "myId":181, "name": "作りま", "prononciation":"Tsukurimasu", "translation":"Construire/ fait", "type": "vb", "family":"kanji",  "level":3},
{ "myId":182, "name": "スポーツ", "prononciation":"", "translation":"Sport", "type": "nom", "family":"katakana",  "level":3},
{ "myId":183, "name": "韓国", "prononciation":" Kankokku", "translation":" Corée du Sud", "type": "nom", "family":"kanji",  "level":3},
{ "myId":184, "name": "読みま", "prononciation":" Yomimasu", "translation":"lire", "type": "vb", "family":"kanji",  "level":3},
{ "myId":185, "name": "番号", "prononciation":" Bangou", "translation":"  Numéro", "type": "nom", "family":"kanji",  "level":3},
{ "myId":186, "name": "弱い", "prononciation":"yowai", "translation":"  faible", "type": "adj", "family":"kanji",  "level":3},
{ "myId":187, "name": "吹kiます", "prononciation":"fukimasu", "translation":"souffler", "type": "vb", "family":"kanji",  "level":3},
{ "myId":188, "name": "晴れ", "prononciation":" Hare", "translation":"ensolleilé", "type": "adj", "family":"kanji",  "level":3},
{ "myId":189, "name": "降る", "prononciation":"furu", "translation":"Pleuvoir", "type": "vb", "family":"kanji",  "level":3},
{ "myId":190, "name": "雨", "prononciation":"Ame", "translation":"Pluit", "type": "nom", "family":"kanji",  "level":3},
{ "myId":191, "name": "空", "prononciation":"Sora", "translation":"Ciel", "type": "nom", "family":"kanji",  "level":3},
{ "myId":192, "name": "雪", "prononciation":"Yuki", "translation":"neige", "type": "nom", "family":"kanji",  "level":3},
{ "myId":193, "name": "外", "prononciation":"Soto ", "translation":"dehors", "type": "nom", "family":"kanji",  "level":3},
{ "myId":194, "name": "朝", "prononciation":"Asa", "translation":"matin", "type": "nom", "family":"kanji",  "level":3},
{ "myId":195, "name": "今晩", "prononciation":"Konban", "translation":"Ce soir", "type": "nom", "family":"kanji",  "level":3},
{ "myId":196, "name": "寒い", "prononciation":"samui", "translation":"froid", "type": "adj", "family":"kanji",  "level":3},
{ "myId":197, "name": "吹いている", "prononciation":"Fuyite imasu", "translation":"Est en train de souffler", "type": "vb", "family":"kanji",  "level":3},
{ "myId":198, "name": "涼しい", "prononciation":"Suzushii", "translation":"frais", "type": "adj", "family":"kanji",  "level":3},
{ "myId":199, "name": "全然", "prononciation":"zenzen", "translation":"Pas du tout", "type": "adv", "family":"kanji",  "level":3},
{ "myId":200, "name": "野菜", "prononciation":"Yasai", "translation":"legumes", "type": "nom", "family":"kanji",  "level":3},
{ "myId":201, "name": "大変", "prononciation":"taihen", "translation":"Beaucoup", "type": "adj", "family":"kanji",  "level":3},
{ "myId":202, "name": "ラーメン", "prononciation":"", "translation":"Ramen", "type": "nom", "family":"katakana",  "level":3},
{ "myId":203, "name": "少ない", "prononciation":"sukunai", "translation":"Pas assez", "type": "adv", "family":"kanji",  "level":3},
{ "myId":204, "name": "お弁当", "prononciation":"Obento", "translation":" Bentô", "type": "nom", "family":"kanji",  "level":3},
{ "myId":205, "name": "塩", "prononciation":"Shio", "translation":"sel", "type": "nom", "family":"kanji",  "level":3},
{ "myId":206, "name": "ご飯", "prononciation":"Gohan", "translation":"riz", "type": "nom", "family":"kanji",  "level":3},
{ "myId":207, "name": "砂糖", "prononciation":"Satou", "translation":"sucre", "type": "nom", "family":"kanji",  "level":3},
{ "myId":208, "name": "全部", "prononciation":"Zenbu", "translation":"tout", "type": "adv", "family":"kanji",  "level":3},
{ "myId":209, "name": "牛乳", "prononciation":"Gyuunyu", "translation":"Lait", "type": "nom", "family":"kanji",  "level":3},
{ "myId":210, "name": "毎朝", "prononciation":"Maiasa", "translation":"Chaque matin", "type": "adv", "family":"kanji",  "level":3},
{ "myId":211, "name": "洗いま", "prononciation":"haraimasu", "translation":"laver", "type": "vb", "family":"kanji",  "level":3},
{ "myId":212, "name": "スプーン", "prononciation":"", "translation":"cuillère", "type": "nom", "family":"katakana",  "level":3},
{ "myId":213, "name": "ボウル", "prononciation":"", "translation":"bol", "type": "nom", "family":"katakana",  "level":3},
{ "myId":214, "name": "欲しい", "prononciation":" oshii", "translation":" Vouloir", "type": "vb", "family":"kanji",  "level":3},
{ "myId":215, "name": "カレー", "prononciation":"", "translation":"curry", "type": "nom", "family":"katakana",  "level":3},
{ "myId":216, "name": "本当Ni", "prononciation":"Hontouni", "translation":"vraiment", "type": "adv", "family":"kanji",  "level":3},
{ "myId":217, "name": "すっぱい", "prononciation":"", "translation":"acide", "type": "nom", "family":"kanji",  "level":3},
{ "myId":218, "name": "塩っぱい", "prononciation":"Chouppai", "translation":"salé", "type": "nom", "family":"kanji",  "level":3},
{ "myId":219, "name": "お箸", "prononciation":"Ohashi", "translation":"baguettes", "type": "nom", "family":"kanji",  "level":3},
{ "myId":220, "name": "茶碗", "prononciation":"Chawan", "translation":"Bol de riz", "type": "nom", "family":"kanji",  "level":3},
{ "myId":221, "name": "広い ", "prononciation":"hiroi", "translation":"Large/spacieux/gros", "type": "nom", "family":"kanji",  "level":3},
{ "myId":222, "name": "病院", "prononciation":"Byouin", "translation":" hopital", "type": "nom", "family":"kanji",  "level":3},
{ "myId":223, "name": "出身", "prononciation":"Shuushin", "translation":"Lieu de naissance", "type": "nom", "family":"kanji",  "level":3},
{ "myId":224, "name": "出口", "prononciation":"Deguchi", "translation":" sortie", "type": "nom", "family":"kanji",  "level":3},
{ "myId":225, "name": "銀行", "prononciation":"Ginkou", "translation":"banque", "type": "nom", "family":"kanji",  "level":4},
{ "myId":226, "name": "長い", "prononciation":"Nagai", "translation":"Long", "type": "adj", "family":"kanji",  "level":4},
{ "myId":227, "name": "店", "prononciation":"Mise", "translation":"magasin", "type": "nom", "family":"kanji",  "level":4},
{ "myId":228, "name": "東", "prononciation":"Higashi", "translation":"est", "type": "nom", "family":"kanji",  "level":4},
{ "myId":229, "name": "西", "prononciation":" nishi", "translation":"  ouest", "type": "nom", "family":"kanji",  "level":4},
{ "myId":230, "name": "北", "prononciation":" Kita", "translation":" nord", "type": "nom", "family":"kanji",  "level":4},
{ "myId":231, "name": "通ります", "prononciation":"Tourimasu", "translation":"Passer(par)", "type": "vb", "family":"kanji",  "level":4},
{ "myId":232, "name": "入ります", "prononciation":"Hairimasu", "translation":"rentrer", "type": "vb", "family":"kanji",  "level":4},
{ "myId":233, "name": "次", "prononciation":"Tsugi", "translation":"prochain", "type": "nom", "family":"kanji",  "level":4},
{ "myId":234, "name": "進みま", "prononciation":"Susumimasu", "translation":"avancer", "type": "vb", "family":"kanji",  "level":4},
{ "myId":235, "name": "", "prononciation":"まっすぐ", "translation":"Tout droit", "type": "adv", "family":"kanji",  "level":4},
{ "myId":236, "name": "曲がります", "prononciation":"Magarimasu", "translation":"tourner", "type": "vb", "family":"kanji",  "level":4},
{ "myId":237, "name": "今年", "prononciation":"Kotoshi", "translation":"Cette année", "type": "adv", "family":"kanji",  "level":4},
{ "myId":238, "name": "月", "prononciation":"Gatsu", "translation":"mois", "type": "nom", "family":"kanji",  "level":4},
{ "myId":239, "name": "去年", "prononciation":"Kyou nen", "translation":" L’année dernière", "type": "adv", "family":"kanji",  "level":4},
{ "myId":240, "name": "誕生日", "prononciation":"Tanjoubi", "translation":"Anniversaire", "type": "nom", "family":"kanji",  "level":4},
{ "myId":241, "name": "お金", "prononciation":"Okane", "translation":"argent", "type": "nom", "family":"kanji",  "level":4},
{ "myId":242, "name": "時計", "prononciation":"Toke", "translation":" horloge", "type": "nom", "family":"kanji",  "level":4},
{ "myId":243, "name": "鞄", "prononciation":"Kaban", "translation":" Sac à dos", "type": "nom", "family":"kanji",  "level":4},
{ "myId":244, "name": "腕", "prononciation":"Ude ", "translation":"bras", "type": "nom", "family":"kanji",  "level":4},
{ "myId":245, "name": "出します", "prononciation":"Dashimasu", "translation":"retirer", "type": "vb", "family":"kanji",  "level":4},
{ "myId":246, "name": "もの", "prononciation":"", "translation":" Thing", "type": "nom", "family":"hiragana",  "level":4},
{ "myId":247, "name": "軽い", "prononciation":"Karui", "translation":"léger", "type": "adj", "family":"kanji",  "level":4},
{ "myId":248, "name": "丈夫", "prononciation":"Joubu", "translation":"Solide/durable", "type": "adj", "family":"kanji",  "level":4},
{ "myId":249, "name": "お土産", "prononciation":"Omiyage", "translation":"souvenir", "type": "nom", "family":"kanji",  "level":4},
{ "myId":250, "name": "もらいました", "prononciation":"", "translation":"emprunter", "type": "vb", "family":"hiragana",  "level":4},
{ "myId":251, "name": "大切", "prononciation":"Taisetsu", "translation":"précieux", "type": "adj", "family":"kanji",  "level":4},
{ "myId":252, "name": "欲しい", "prononciation":" Oshii", "translation":"vouloir", "type": "vb", "family":"kanji",  "level":4},
{ "myId":253, "name": "違う", "prononciation":"Chigau", "translation":" different", "type": "adv", "family":"kanji",  "level":4},
{ "myId":254, "name": "買い物", "prononciation":"Kaimono", "translation":"shopping", "type": "vb", "family":"kanji",  "level":4},
{ "myId":255, "name": "汚い", "prononciation":"Kitanai", "translation":"dégueulsse", "type": "adj", "family":"kanji",  "level":4},
{ "myId":256, "name": "在宅", "prononciation":"Zaitaku", "translation":"À la maison", "type": "adv", "family":"kanji",  "level":4},
{ "myId":257, "name": "立派", "prononciation":" rippa", "translation":" Splendide", "type": "adj", "family":"kanji",  "level":4},
{ "myId":258, "name": "方", "prononciation":" Kata/ hou", "translation":" personne", "type": "nom", "family":"kanji",  "level":4},
{ "myId":259, "name": "皆さん", "prononciation":" Minna san", "translation":"Tout le monde", "type": "nom", "family":"kanji",  "level":4},
{ "myId":260, "name": "離婚", "prononciation":"rikkon", "translation":" divorcer", "type": "vb", "family":"kanji",  "level":4},
{ "myId":261, "name": "結婚", "prononciation":" Kekkon", "translation":" Se marier", "type": "vb", "family":"kanji",  "level":4},
{ "myId":262, "name": "別れます", "prononciation":" Wakaremasu", "translation":"  rompre", "type": "vb", "family":"kanji",  "level":4},
{ "myId":263, "name": "赤ちゃん", "prononciation":"Akachan", "translation":"Bébé", "type": "nom", "family":"kanji",  "level":4},
{ "myId":264, "name": "呼びます", "prononciation":"Youbimasu", "translation":"Appeler", "type": "vb", "family":"kanji",  "level":4},
{ "myId":265, "name": "洗濯", "prononciation":"Sentaku", "translation":"faire la lessive", "type": "vb", "family":"kanji",  "level":4},
{ "myId":266, "name": "シャワー", "prononciation":"", "translation":"douche", "type": "nom", "family":"kanji",  "level":4},
{ "myId":267, "name": "手紙", "prononciation":"Tegami", "translation":"lettre", "type": "nom", "family":"kanji",  "level":4},
{ "myId":268, "name": "開けます", "prononciation":" Akemasu", "translation":" ouvrir", "type": "vb", "family":"kanji",  "level":4},
{ "myId":269, "name": "立って", "prononciation":"Tatte", "translation":"debout", "type": "vb", "family":"kanji",  "level":4},
{ "myId":270, "name": "立ちます", "prononciation":"Tachimasu", "translation":"Se lever", "type": "vb", "family":"kanji",  "level":4},
{ "myId":271, "name": "つけte", "prononciation":"", "translation":"Allumer", "type": "vb", "family":"hiragana",  "level":4},
{ "myId":272, "name": "紅茶", "prononciation":"Kocha", "translation":"Thé noir", "type": "nom", "family":"kanji",  "level":4},
{ "myId":273, "name": "起きまSu", "prononciation":"Okimasu", "translation":" Se lever", "type": "vb", "family":"kanji",  "level":4},
{ "myId":274, "name": "ドア", "prononciation":"", "translation":"door", "type": "nom", "family":"katakana",  "level":4},
{ "myId":275, "name": "始まります", "prononciation":"hajimemasu", "translation":" commencer", "type": "vb", "family":"kanji",  "level":4},
{ "myId":276, "name": "宿題", "prononciation":"Shikudai", "translation":" devoirs", "type": "nom", "family":"kanji",  "level":4},
{ "myId":277, "name": "終わりま", "prononciation":"Owarimasu", "translation":" Finir", "type": "vb", "family":"kanji",  "level":4},
{ "myId":278, "name": "テスト", "prononciation":"", "translation":"Examen", "type": "nom", "family":"katakana",  "level":4},
{ "myId":279, "name": "難しI", "prononciation":" Muzukashi", "translation":" Difficile", "type": "adj", "family":"kanji",  "level":4},
{ "myId":280, "name": "覚えます", "prononciation":"Oboemasu", "translation":"Mémorise/Se souvenir", "type": "vb", "family":"kanji",  "level":4},
{ "myId":281, "name": "言葉", "prononciation":" Kotoba", "translation":" Mots", "type": "nom", "family":"kanji",  "level":4},
{ "myId":282, "name": "教えて", "prononciation":"hiki", "translation":"Montre/dire", "type": "vb", "family":"kanji",  "level":4},
{ "myId":283, "name": "引きます", "prononciation":"Hikimasu", "translation":" Consulter", "type": "vb", "family":"kanji",  "level":4},
{ "myId":284, "name": "花瓶", "prononciation":"Kabin", "translation":" vase", "type": "nom", "family":"kanji",  "level":4},
{ "myId":285, "name": "登ります", "prononciation":"Noborimasu", "translation":" grimper", "type": "vb", "family":"kanji",  "level":4},
{ "myId":286, "name": "川", "prononciation":" Kawa", "translation":" riviere", "type": "nom", "family":"kanji",  "level":4},
{ "myId":287, "name": "声", "prononciation":" Koe", "translation":"  voix", "type": "nom", "family":"kanji",  "level":4},
{ "myId":288, "name": "賑やか", "prononciation":"Nigiyaka", "translation":" Animé/blindé", "type": "nom", "family":"kanji",  "level":4},
{ "myId":289, "name": "さる", "prononciation":"", "translation":" singe", "type": "nom", "family":"hiragana",  "level":4},
{ "myId":290, "name": "動物", "prononciation":"Doubutsu", "translation":" animaux", "type": "nom", "family":"kanji",  "level":4},
{ "myId":291, "name": "飛びます", "prononciation":"Tobimasu", "translation":"S'envoler", "type": "vb", "family":"kanji",  "level":4},
]

export default japKanjiData;